// frontend/components/ui/Modal.tsx
'use client'

import React, { useEffect } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { createPortal } from 'react-dom'

export interface ModalProps {
  isOpen: boolean
  onClose: () => void
  title?: string
  children: React.ReactNode
  size?: 'sm' | 'md' | 'lg' | 'xl' | 'full'
  closable?: boolean
  maskClosable?: boolean
  footer?: React.ReactNode
  className?: string
}

export const Modal: React.FC<ModalProps> = ({
  isOpen,
  onClose,
  title,
  children,
  size = 'md',
  closable = true,
  maskClosable = true,
  footer,
  className = ''
}) => {
  const sizeClasses = {
    sm: 'max-w-md',
    md: 'max-w-lg',
    lg: 'max-w-2xl',
    xl: 'max-w-4xl',
    full: 'max-w-[95vw] max-h-[95vh]'
  }

  // 处理 ESC 键关闭
  useEffect(() => {
    const handleEscape = (e: KeyboardEvent) => {
      if (e.key === 'Escape' && closable && isOpen) {
        onClose()
      }
    }

    if (isOpen) {
      document.addEventListener('keydown', handleEscape)
      document.body.style.overflow = 'hidden'
    }

    return () => {
      document.removeEventListener('keydown', handleEscape)
      document.body.style.overflow = 'unset'
    }
  }, [isOpen, closable, onClose])

  if (typeof window === 'undefined') {
    return null
  }

  return createPortal(
    <AnimatePresence>
      {isOpen && (
        <div className="fixed inset-0 z-50 overflow-y-auto">
          {/* 遮罩层 */}
          <motion.div
            className="fixed inset-0 bg-black/40 backdrop-blur-sm"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            transition={{ duration: 0.2 }}
            onClick={maskClosable ? onClose : undefined}
          />
          
          {/* 模态框容器 */}
          <div className="flex min-h-full items-center justify-center p-4">
            <motion.div
              className={`
                relative w-full ${sizeClasses[size]}
                bg-white/95 backdrop-blur-xl
                rounded-ios-2xl shadow-ios-2xl
                border border-white/20
                ${className}
              `}
              initial={{ opacity: 0, scale: 0.9, y: 20 }}
              animate={{ opacity: 1, scale: 1, y: 0 }}
              exit={{ opacity: 0, scale: 0.9, y: 20 }}
              transition={{ 
                type: "spring", 
                stiffness: 400, 
                damping: 30,
                duration: 0.3
              }}
              onClick={(e) => e.stopPropagation()}
            >
              {/* 标题栏 */}
              {(title || closable) && (
                <div className="flex items-center justify-between p-6 border-b border-gray-200/50">
                  <h3 className="text-xl font-semibold text-gray-900">
                    {title}
                  </h3>
                  {closable && (
                    <motion.button
                      onClick={onClose}
                      className="p-2 hover:bg-gray-100/50 rounded-ios-lg transition-colors"
                      whileHover={{ scale: 1.05 }}
                      whileTap={{ scale: 0.95 }}
                    >
                      <svg className="w-5 h-5 text-gray-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                      </svg>
                    </motion.button>
                  )}
                </div>
              )}
              
              {/* 内容区域 */}
              <div className="p-6">
                {children}
              </div>
              
              {/* 底部操作区 */}
              {footer && (
                <div className="flex items-center justify-end space-x-3 p-6 border-t border-gray-200/50">
                  {footer}
                </div>
              )}
            </motion.div>
          </div>
        </div>
      )}
    </AnimatePresence>,
    document.body
  )
}

// 确认对话框组件
export interface ConfirmModalProps {
  isOpen: boolean
  onClose: () => void
  onConfirm: () => void
  title?: string
  message: string
  confirmText?: string
  cancelText?: string
  type?: 'info' | 'warning' | 'danger'
}

export const ConfirmModal: React.FC<ConfirmModalProps> = ({
  isOpen,
  onClose,
  onConfirm,
  title,
  message,
  confirmText = '确认',
  cancelText = '取消',
  type = 'info'
}) => {
  const typeStyles = {
    info: {
      icon: 'ℹ️',
      confirmBg: 'bg-ios18-blue hover:bg-blue-600'
    },
    warning: {
      icon: '⚠️',
      confirmBg: 'bg-yellow-500 hover:bg-yellow-600'
    },
    danger: {
      icon: '❌',
      confirmBg: 'bg-red-500 hover:bg-red-600'
    }
  }

  const style = typeStyles[type]

  const handleConfirm = () => {
    onConfirm()
    onClose()
  }

  return (
    <Modal
      isOpen={isOpen}
      onClose={onClose}
      title={title}
      size="sm"
    >
      <div className="text-center space-y-4">
        <div className="text-4xl">{style.icon}</div>
        <p className="text-gray-700 text-base leading-relaxed">
          {message}
        </p>
      </div>
      
      <div className="flex items-center justify-center space-x-3 mt-6">
        <motion.button
          onClick={onClose}
          className="px-4 py-2 bg-gray-100 text-gray-700 rounded-ios-lg hover:bg-gray-200 transition-colors font-medium"
          whileHover={{ scale: 1.02 }}
          whileTap={{ scale: 0.98 }}
        >
          {cancelText}
        </motion.button>
        <motion.button
          onClick={handleConfirm}
          className={`px-4 py-2 ${style.confirmBg} text-white rounded-ios-lg transition-colors font-medium`}
          whileHover={{ scale: 1.02 }}
          whileTap={{ scale: 0.98 }}
        >
          {confirmText}
        </motion.button>
      </div>
    </Modal>
  )
}

// frontend-vue/src/components/ui/Modal.tsx
import { defineComponent, type PropType, onMounted, onUnmounted, Teleport, Transition } from 'vue'

export interface ModalProps {
  isOpen: boolean
  onClose: () => void
  title?: string
  size?: 'sm' | 'md' | 'lg' | 'xl' | '2xl' | '3xl' | 'full'
  closable?: boolean
  maskClosable?: boolean
  footer?: any
  className?: string
}

export const Modal = defineComponent({
  name: 'Modal',
  props: {
    isOpen: {
      type: Boolean,
      required: true
    },
    onClose: {
      type: Function as PropType<() => void>,
      required: true
    },
    title: String,
    size: {
      type: String as PropType<ModalProps['size']>,
      default: 'md'
    },
    closable: {
      type: Boolean,
      default: true
    },
    maskClosable: {
      type: Boolean,
      default: true
    },
    footer: Object,
    className: {
      type: String,
      default: ''
    }
  },
  setup(props, { slots }) {
    const sizeClasses = {
      sm: 'max-w-md',
      md: 'max-w-lg',
      lg: 'max-w-2xl',
      xl: 'max-w-4xl',
      '2xl': 'max-w-6xl',
      '3xl': 'max-w-7xl max-h-[80vh]',
      full: 'max-w-[95vw] max-h-[95vh]'
    }

    // 处理 ESC 键关闭
    const handleEscape = (e: KeyboardEvent) => {
      if (e.key === 'Escape' && props.closable && props.isOpen) {
        props.onClose()
      }
    }

    onMounted(() => {
      if (props.isOpen) {
        document.addEventListener('keydown', handleEscape)
        document.body.style.overflow = 'hidden'
      }
    })

    onUnmounted(() => {
      document.removeEventListener('keydown', handleEscape)
      document.body.style.overflow = 'unset'
    })

    const handleMaskClick = () => {
      if (props.maskClosable) {
        props.onClose()
      }
    }

    const handleContentClick = (e: Event) => {
      e.stopPropagation()
    }

    return () => (
      <Teleport to="body">
        <Transition
          enterActiveClass="transition-opacity duration-200"
          leaveActiveClass="transition-opacity duration-200"
          enterFromClass="opacity-0"
          enterToClass="opacity-100"
          leaveFromClass="opacity-100"
          leaveToClass="opacity-0"
        >
          {props.isOpen && (
            <div class="fixed inset-0 z-50 overflow-y-auto">
              {/* 遮罩层 */}
              <div
                class="fixed inset-0 bg-black/40 backdrop-blur-sm"
                onClick={handleMaskClick}
              />
              
              {/* 模态框容器 */}
              <div class="flex min-h-full items-center justify-center p-4">
                <div
                  class={`
                    relative w-full ${sizeClasses[props.size!]}
                    bg-white/95 backdrop-blur-xl
                    rounded-ios-2xl shadow-ios-2xl
                    border border-white/20
                    ${props.className}
                  `}
                  style={{
                    animation: 'modalEnter 0.3s ease-out'
                  }}
                  onClick={handleContentClick}
                >
                  {/* 标题栏 */}
                  {(props.title || props.closable) && (
                    <div class="flex items-center justify-between p-6 border-b border-gray-200/50">
                      <h3 class="text-xl font-semibold text-gray-900">
                        {props.title}
                      </h3>
                      {props.closable && (
                        <button
                          onClick={props.onClose}
                          class="p-2 hover:bg-gray-100/50 rounded-ios-lg transition-colors"
                        >
                          <svg class="w-5 h-5 text-gray-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                          </svg>
                        </button>
                      )}
                    </div>
                  )}
                  
                  {/* 内容区域 */}
                  <div class={`p-6 ${props.size === '3xl' ? 'max-h-[60vh] overflow-y-auto' : ''}`}>
                    {slots.default?.()}
                  </div>
                  
                  {/* 底部操作区 */}
                  {props.footer && (
                    <div class="flex items-center justify-end space-x-3 p-6 border-t border-gray-200/50">
                      {props.footer}
                    </div>
                  )}
                </div>
              </div>
            </div>
          )}
        </Transition>
      </Teleport>
    )
  }
})

// 确认对话框组件
export interface ConfirmModalProps {
  isOpen: boolean
  onClose: () => void
  onConfirm: () => void
  title?: string
  message: string
  confirmText?: string
  cancelText?: string
  type?: 'info' | 'warning' | 'danger'
}

export const ConfirmModal = defineComponent({
  name: 'ConfirmModal',
  props: {
    isOpen: {
      type: Boolean,
      required: true
    },
    onClose: {
      type: Function as PropType<() => void>,
      required: true
    },
    onConfirm: {
      type: Function as PropType<() => void>,
      required: true
    },
    title: String,
    message: {
      type: String,
      required: true
    },
    confirmText: {
      type: String,
      default: '确认'
    },
    cancelText: {
      type: String,
      default: '取消'
    },
    type: {
      type: String as PropType<ConfirmModalProps['type']>,
      default: 'info'
    }
  },
  setup(props) {
    const typeStyles = {
      info: {
        icon: 'ℹ️',
        confirmBg: 'bg-ios18-blue hover:bg-blue-600'
      },
      warning: {
        icon: '⚠️',
        confirmBg: 'bg-yellow-500 hover:bg-yellow-600'
      },
      danger: {
        icon: '❌',
        confirmBg: 'bg-red-500 hover:bg-red-600'
      }
    }

    const style = typeStyles[props.type!]

    const handleConfirm = () => {
      props.onConfirm()
      props.onClose()
    }

    return () => (
      <Modal
        isOpen={props.isOpen}
        onClose={props.onClose}
        title={props.title}
        size="sm"
      >
        <div class="text-center space-y-4">
          <div class="text-4xl">{style.icon}</div>
          <p class="text-gray-700 text-base leading-relaxed">
            {props.message}
          </p>
        </div>
        
        <div class="flex items-center justify-center space-x-3 mt-6">
          <button
            onClick={props.onClose}
            class="px-4 py-2 bg-gray-100 text-gray-700 rounded-ios-lg hover:bg-gray-200 transition-colors font-medium"
          >
            {props.cancelText}
          </button>
          <button
            onClick={handleConfirm}
            class={`px-4 py-2 ${style.confirmBg} text-white rounded-ios-lg transition-colors font-medium`}
          >
            {props.confirmText}
          </button>
        </div>
      </Modal>
    )
  }
})
