// frontend/components/ui/Tooltip.tsx
'use client'

import React, { useState, useRef, useEffect } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { createPortal } from 'react-dom'

export interface TooltipProps {
  children: React.ReactNode
  content: React.ReactNode
  placement?: 'top' | 'bottom' | 'left' | 'right' | 'top-start' | 'top-end' | 'bottom-start' | 'bottom-end'
  trigger?: 'hover' | 'click' | 'focus' | 'manual'
  delay?: number
  disabled?: boolean
  className?: string
  visible?: boolean
  onVisibleChange?: (visible: boolean) => void
}

export const Tooltip: React.FC<TooltipProps> = ({
  children,
  content,
  placement = 'top',
  trigger = 'hover',
  delay = 100,
  disabled = false,
  className = '',
  visible,
  onVisibleChange
}) => {
  const [internalVisible, setInternalVisible] = useState(false)
  const [position, setPosition] = useState({ x: 0, y: 0 })
  const triggerRef = useRef<HTMLDivElement>(null)
  const tooltipRef = useRef<HTMLDivElement>(null)
  const timeoutRef = useRef<NodeJS.Timeout>()

  const isVisible = visible !== undefined ? visible : internalVisible

  // 计算工具提示位置
  const calculatePosition = () => {
    if (!triggerRef.current || !tooltipRef.current) return

    const triggerRect = triggerRef.current.getBoundingClientRect()
    const tooltipRect = tooltipRef.current.getBoundingClientRect()
    const scrollX = window.pageXOffset
    const scrollY = window.pageYOffset

    let x = 0
    let y = 0

    switch (placement) {
      case 'top':
        x = triggerRect.left + triggerRect.width / 2 - tooltipRect.width / 2
        y = triggerRect.top - tooltipRect.height - 8
        break
      case 'top-start':
        x = triggerRect.left
        y = triggerRect.top - tooltipRect.height - 8
        break
      case 'top-end':
        x = triggerRect.right - tooltipRect.width
        y = triggerRect.top - tooltipRect.height - 8
        break
      case 'bottom':
        x = triggerRect.left + triggerRect.width / 2 - tooltipRect.width / 2
        y = triggerRect.bottom + 8
        break
      case 'bottom-start':
        x = triggerRect.left
        y = triggerRect.bottom + 8
        break
      case 'bottom-end':
        x = triggerRect.right - tooltipRect.width
        y = triggerRect.bottom + 8
        break
      case 'left':
        x = triggerRect.left - tooltipRect.width - 8
        y = triggerRect.top + triggerRect.height / 2 - tooltipRect.height / 2
        break
      case 'right':
        x = triggerRect.right + 8
        y = triggerRect.top + triggerRect.height / 2 - tooltipRect.height / 2
        break
    }

    // 边界检测
    const viewportWidth = window.innerWidth
    const viewportHeight = window.innerHeight

    if (x < 0) x = 8
    if (x + tooltipRect.width > viewportWidth) x = viewportWidth - tooltipRect.width - 8
    if (y < 0) y = 8
    if (y + tooltipRect.height > viewportHeight) y = viewportHeight - tooltipRect.height - 8

    setPosition({ x: x + scrollX, y: y + scrollY })
  }

  // 显示工具提示
  const showTooltip = () => {
    if (disabled) return
    
    if (timeoutRef.current) {
      clearTimeout(timeoutRef.current)
    }

    timeoutRef.current = setTimeout(() => {
      setInternalVisible(true)
      onVisibleChange?.(true)
    }, delay)
  }

  // 隐藏工具提示
  const hideTooltip = () => {
    if (timeoutRef.current) {
      clearTimeout(timeoutRef.current)
    }

    setInternalVisible(false)
    onVisibleChange?.(false)
  }

  // 事件处理
  const handleMouseEnter = () => {
    if (trigger === 'hover') showTooltip()
  }

  const handleMouseLeave = () => {
    if (trigger === 'hover') hideTooltip()
  }

  const handleClick = () => {
    if (trigger === 'click') {
      if (isVisible) {
        hideTooltip()
      } else {
        showTooltip()
      }
    }
  }

  const handleFocus = () => {
    if (trigger === 'focus') showTooltip()
  }

  const handleBlur = () => {
    if (trigger === 'focus') hideTooltip()
  }

  // 位置更新
  useEffect(() => {
    if (isVisible) {
      calculatePosition()
      
      const handleResize = () => calculatePosition()
      const handleScroll = () => calculatePosition()
      
      window.addEventListener('resize', handleResize)
      window.addEventListener('scroll', handleScroll)
      
      return () => {
        window.removeEventListener('resize', handleResize)
        window.removeEventListener('scroll', handleScroll)
      }
    }
  }, [isVisible, placement])

  // 清理定时器
  useEffect(() => {
    return () => {
      if (timeoutRef.current) {
        clearTimeout(timeoutRef.current)
      }
    }
  }, [])

  // 获取箭头样式
  const getArrowStyle = () => {
    const arrowSize = 6
    const baseStyle = `absolute w-0 h-0 border-solid`
    
    switch (placement) {
      case 'top':
      case 'top-start':
      case 'top-end':
        return `${baseStyle} top-full left-1/2 transform -translate-x-1/2 border-l-${arrowSize} border-r-${arrowSize} border-t-${arrowSize} border-l-transparent border-r-transparent border-t-gray-900`
      case 'bottom':
      case 'bottom-start':
      case 'bottom-end':
        return `${baseStyle} bottom-full left-1/2 transform -translate-x-1/2 border-l-${arrowSize} border-r-${arrowSize} border-b-${arrowSize} border-l-transparent border-r-transparent border-b-gray-900`
      case 'left':
        return `${baseStyle} left-full top-1/2 transform -translate-y-1/2 border-t-${arrowSize} border-b-${arrowSize} border-l-${arrowSize} border-t-transparent border-b-transparent border-l-gray-900`
      case 'right':
        return `${baseStyle} right-full top-1/2 transform -translate-y-1/2 border-t-${arrowSize} border-b-${arrowSize} border-r-${arrowSize} border-t-transparent border-b-transparent border-r-gray-900`
      default:
        return ''
    }
  }

  if (typeof window === 'undefined') {
    return <div className={`inline-block ${className}`}>{children}</div>
  }

  return (
    <>
      <div
        ref={triggerRef}
        className={`inline-block ${className}`}
        onMouseEnter={handleMouseEnter}
        onMouseLeave={handleMouseLeave}
        onClick={handleClick}
        onFocus={handleFocus}
        onBlur={handleBlur}
      >
        {children}
      </div>

      {createPortal(
        <AnimatePresence>
          {isVisible && (
            <motion.div
              ref={tooltipRef}
              className="fixed z-50 px-3 py-2 text-sm text-white bg-gray-900 rounded-ios-lg shadow-ios-lg max-w-xs break-words"
              style={{
                left: position.x,
                top: position.y
              }}
              initial={{ opacity: 0, scale: 0.8 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.8 }}
              transition={{ duration: 0.15 }}
            >
              {content}
              <div className={getArrowStyle()} />
            </motion.div>
          )}
        </AnimatePresence>,
        document.body
      )}
    </>
  )
}

// frontend-vue/src/components/ui/Tooltip.tsx
import { defineComponent, ref, computed, onMounted, onUnmounted, nextTick, type PropType, type CSSProperties } from 'vue'
import { Teleport, Transition } from 'vue'

export interface TooltipProps {
  children?: any
  content: any
  placement?: 'top' | 'bottom' | 'left' | 'right' | 'top-start' | 'top-end' | 'bottom-start' | 'bottom-end'
  trigger?: 'hover' | 'click' | 'focus' | 'manual'
  delay?: number
  disabled?: boolean
  className?: string
  visible?: boolean
  onVisibleChange?: (visible: boolean) => void
}

export const Tooltip = defineComponent({
  name: 'Tooltip',
  props: {
    content: {
      required: true
    },
    placement: {
      type: String as PropType<TooltipProps['placement']>,
      default: 'top'
    },
    trigger: {
      type: String as PropType<TooltipProps['trigger']>,
      default: 'hover'
    },
    delay: {
      type: Number,
      default: 100
    },
    disabled: {
      type: Boolean,
      default: false
    },
    className: {
      type: String,
      default: ''
    },
    visible: Boolean,
    onVisibleChange: Function as PropType<(visible: boolean) => void>
  },
  setup(props, { slots, emit }) {
    const internalVisible = ref(false)
    const position = ref({ x: 0, y: 0 })
    const isMounted = ref(false)
    const triggerRef = ref<HTMLDivElement>()
    const tooltipRef = ref<HTMLDivElement>()
    const timeoutRef = ref<number>()

    // 确保只在客户端挂载后才添加交互属性
    onMounted(() => {
      isMounted.value = true
    })

    const isVisible = computed(() => 
      props.visible !== undefined ? props.visible : internalVisible.value
    )

    // 计算工具提示位置
    const calculatePosition = () => {
      if (!triggerRef.value) return { x: 0, y: 0 }

      const triggerRect = triggerRef.value.getBoundingClientRect()
      const scrollX = window.pageXOffset || document.documentElement.scrollLeft
      const scrollY = window.pageYOffset || document.documentElement.scrollTop

      let x = 0
      let y = 0

      // 简化位置计算
      switch (props.placement) {
        case 'top':
          x = triggerRect.left + triggerRect.width / 2
          y = triggerRect.top - 8
          break
        case 'bottom':
          x = triggerRect.left + triggerRect.width / 2
          y = triggerRect.bottom + 8
          break
        case 'left':
          x = triggerRect.left - 8
          y = triggerRect.top + triggerRect.height / 2
          break
        case 'right':
          x = triggerRect.right + 8
          y = triggerRect.top + triggerRect.height / 2
          break
        default:
          x = triggerRect.left + triggerRect.width / 2
          y = triggerRect.top - 8
      }

      return { x: x + scrollX, y: y + scrollY }
    }

    // 显示工具提示
    const showTooltip = () => {
      if (props.disabled) return
      
      if (timeoutRef.value) {
        clearTimeout(timeoutRef.value)
      }

      if (props.delay > 0) {
        timeoutRef.value = window.setTimeout(() => {
          internalVisible.value = true
          props.onVisibleChange?.(true)
          emit('visible-change', true)
        }, props.delay)
      } else {
        internalVisible.value = true
        props.onVisibleChange?.(true)
        emit('visible-change', true)
      }
    }

    // 隐藏工具提示
    const hideTooltip = () => {
      if (timeoutRef.value) {
        clearTimeout(timeoutRef.value)
      }

      internalVisible.value = false
      props.onVisibleChange?.(false)
      emit('visible-change', false)
    }

    // 事件处理
    const handleMouseEnter = () => {
      if (props.trigger === 'hover') showTooltip()
    }

    const handleMouseLeave = () => {
      if (props.trigger === 'hover') hideTooltip()
    }

    const handleClick = () => {
      if (props.trigger === 'click') {
        if (isVisible.value) {
          hideTooltip()
        } else {
          showTooltip()
        }
      }
    }

    const handleFocus = () => {
      if (props.trigger === 'focus') showTooltip()
    }

    const handleBlur = () => {
      if (props.trigger === 'focus') hideTooltip()
    }

    // 位置更新
    const updatePosition = () => {
      if (isVisible.value && triggerRef.value) {
        nextTick(() => {
          const newPosition = calculatePosition()
          position.value = newPosition
        })
      }
    }

    // 监听位置变化
    const handleResize = () => updatePosition()
    const handleScroll = () => updatePosition()

    onMounted(() => {
      window.addEventListener('resize', handleResize)
      window.addEventListener('scroll', handleScroll)
    })

    onUnmounted(() => {
      window.removeEventListener('resize', handleResize)
      window.removeEventListener('scroll', handleScroll)
      if (timeoutRef.value) {
        clearTimeout(timeoutRef.value)
      }
    })

    // 监听visible状态变化，更新位置
    const unwatchVisible = computed(() => {
      if (isVisible.value) {
        nextTick(() => {
          updatePosition()
        })
      }
      return isVisible.value
    })

    // 获取箭头样式 - 简化版本
    const getArrowStyle = (): CSSProperties => {
      return {
        position: 'absolute',
        width: 0,
        height: 0,
        borderStyle: 'solid',
        borderWidth: '4px',
        borderColor: 'transparent',
        display: 'none' // 暂时隐藏箭头，先确保tooltip本身工作
      }
    }

    // 获取触发器属性
    const getTriggerProps = () => {
      const triggerProps: any = {
        ref: triggerRef,
        class: `inline-block ${props.className}`,
        onMouseenter: handleMouseEnter,
        onMouseleave: handleMouseLeave,
        onClick: handleClick,
        onFocus: handleFocus,
        onBlur: handleBlur
      }

      // 只在客户端挂载后添加交互属性，避免SSR不匹配
      if (isMounted.value) {
        if (props.trigger === 'focus') {
          triggerProps.tabindex = 0
        }
        if (props.trigger === 'click') {
          triggerProps.role = 'button'
        }
      }

      return triggerProps
    }

    return () => (
      <>
        <div {...getTriggerProps()}>
          {slots.default?.()}
        </div>

        <Teleport to="body">
          <Transition
            enterActiveClass="transition-all duration-150"
            leaveActiveClass="transition-all duration-150"
            enterFromClass="opacity-0 scale-80"
            enterToClass="opacity-100 scale-100"
            leaveFromClass="opacity-100 scale-100"
            leaveToClass="opacity-0 scale-80"
          >
            {isVisible.value && (
              <div
                ref={tooltipRef}
                class="fixed z-50 px-3 py-2 text-sm text-white bg-gray-900 rounded-ios-lg shadow-ios-lg max-w-xs break-words"
                style={{
                  left: `${position.value.x}px`,
                  top: `${position.value.y}px`
                }}
              >
                {typeof props.content === 'string' ? props.content : props.content}
                <div style={getArrowStyle()} />
              </div>
            )}
          </Transition>
        </Teleport>
      </>
    )
  }
})
